# Generated by Django 6.0.4 on 2026-04-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('curso', models.CharField(max_length=100)),
                ('periodo', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('git', models.URLField()),
                ('linked', models.URLField()),
                ('url_imagem', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Informações Pessoais',
            },
        ),
    ]
